import logging
import requests
from typing import Optional

logger = logging.getLogger(__name__)

_telegraph_token: Optional[str] = None


def _get_telegraph_poster():
    """Initializes or retrieves TelegraphPoster instance reusing token"""
    global _telegraph_token
    try:
        from html_telegraph_poster import TelegraphPoster

        poster = TelegraphPoster(use_api=True)
        if _telegraph_token:
            poster.access_token = _telegraph_token
        else:
            poster.create_api_token("Feedygram")
            _telegraph_token = poster.access_token
        return poster
    except Exception as e:
        logger.warning("Unable to initialize TelegraphPoster: %s", str(e))
        return None


def _post_html_to_telegraph(title: str, html_content: str) -> Optional[str]:
    """Publishes clean HTML content to Telegraph without uploading external images"""
    if not html_content or not html_content.strip():
        return None
    try:
        poster = _get_telegraph_poster()
        if poster:
            clean_title = (title or "News Update")[:128]
            try:
                res = poster.post(title=clean_title, author="Feedygram", text=html_content, upload_images=False)
            except TypeError:
                res = poster.post(title=clean_title, author="Feedygram", text=html_content)
            if res and isinstance(res, dict) and "url" in res:
                return str(res["url"])
    except Exception as e:
        logger.warning("Error publishing to Telegraph: %s", str(e))
    return None


def _try_trafilatura(url: str, title: str = "") -> Optional[str]:
    """
    Tier 1: Extracts clean article content via Trafilatura (removes menus, cookies, sidebars, ads)
    and publishes it to Telegraph.
    """
    try:
        import trafilatura

        downloaded = trafilatura.fetch_url(url)
        if downloaded:
            extracted_html = trafilatura.extract(
                downloaded,
                output_format="xml",
                include_links=True,
                include_images=True,
                include_formatting=True,
            )
            if extracted_html and len(extracted_html.strip()) > 50:
                # Normalize XML tags generated by Trafilatura to HTML for Telegraph
                clean_html = extracted_html.replace("<doc>", "<div>").replace("</doc>", "</div>")
                telegraph_url = _post_html_to_telegraph(title or "Article", clean_html)
                if telegraph_url:
                    logger.info("Telegraph conversion successful via Trafilatura: %s", telegraph_url)
                    return telegraph_url
    except Exception as e:
        logger.debug("Tier 1 (Trafilatura) failed for %s: %s", url, str(e))
    return None


def _try_webpage2telegraph(url: str) -> Optional[str]:
    """
    Tier 2: Attempts conversion via webpage2telegraph.
    """
    try:
        import webpage2telegraph

        res = webpage2telegraph.transfer(url)
        if res and str(res).startswith("http") and "telegra.ph" in str(res):
            logger.info("Telegraph conversion successful via webpage2telegraph: %s", str(res))
            return str(res)
    except Exception as e:
        logger.debug("Tier 2 (webpage2telegraph) failed for %s: %s", url, str(e))
    return None


def convert_to_instant_link(url: str, title: str = "") -> str:
    """
    Instant View / Telegraph Link conversion pipeline:
    1. Tier 1: Trafilatura (clean article extraction without navbar/cookie popups) -> Telegraph
    2. Tier 2: webpage2telegraph -> Telegraph
    3. Final Fallback: Original URL (avoids raw markdown or broken output)
    """
    if not url:
        return ""

    # 1. Try Tier 1 (Trafilatura -> Telegraph)
    link = _try_trafilatura(url, title)
    if link:
        return link

    # 2. Fallback Tier 2 (webpage2telegraph)
    link = _try_webpage2telegraph(url)
    if link:
        return link

    # 3. Final Fallback: Original URL
    logger.info("Telegraph conversion not available, using original link: %s", url)
    return url

