name: Build and Push Docker Image (Raspberry Pi)

on:
  push:
    branches: [ "main" ]

jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Raspberry Pi Image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64,linux/arm/v7
          push: true
          tags: duccioo/feedergraph:raspberrypi
